services:
  # Web service for API endpoints
  - type: web
    name: livekit-agent-api
    runtime: python3
    buildCommand: |
      pip install --upgrade pip &&
      pip install -r requirements.txt &&
      mkdir -p model_cache/huggingface &&
      python -c "
      import sys
      try:
          from livekit.agents import cli
          print('LiveKit agents installed successfully')
      except Exception as e:
          print(f'Error importing LiveKit: {e}')
          sys.exit(1)
      "
    startCommand: python agent.py
    plan: starter
    healthCheckPath: /health
    envVars:
      - key: LIVEKIT_URL
        sync: false
      - key: LIVEKIT_API_KEY
        sync: false
      - key: LIVEKIT_API_SECRET
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: CARTESIA_API_KEY
        sync: false
      - key: DEEPGRAM_API_KEY
        sync: false
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: PYTHONPATH
        value: "/opt/render/project/src"
      - key: HF_HOME
        value: "/tmp/model_cache"
      - key: RENDER_SERVICE_TYPE
        value: "web"

  # Background service for LiveKit worker
  - type: background
    name: livekit-agent-worker
    runtime: python3
    buildCommand: |
      pip install --upgrade pip &&
      pip install -r requirements.txt &&
      mkdir -p model_cache/huggingface
    startCommand: python -c "
    import os
    from livekit.agents import cli, WorkerOptions
    from agent import entrypoint, prewarm
    
    # Run only the LiveKit worker
    cli.run_app(WorkerOptions(
        entrypoint_fnc=entrypoint,
        prewarm_fnc=prewarm,
        ws_timeout=30.0,
        agent_name='voice-interviewer'
    ))
    "
    plan: starter
    envVars:
      - key: LIVEKIT_URL
        sync: false
      - key: LIVEKIT_API_KEY
        sync: false
      - key: LIVEKIT_API_SECRET
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: CARTESIA_API_KEY
        sync: false
      - key: DEEPGRAM_API_KEY
        sync: false
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: PYTHONPATH
        value: "/opt/render/project/src"
      - key: HF_HOME
        value: "/tmp/model_cache"